package com.fung.wx.model;

public class WxMenuSetting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wx_menuset.Id
     *
     * @mbggenerated Wed Sep 10 14:07:43 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wx_menuset.menu_name
     *
     * @mbggenerated Wed Sep 10 14:07:43 CST 2014
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wx_menuset.menu_type
     *
     * @mbggenerated Wed Sep 10 14:07:43 CST 2014
     */
    private String menuType;
    
    
    private int parent;

    public int getParent() {
		return parent;
	}

	public void setParent(int parent) {
		this.parent = parent;
	} 

	private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wx_menuset.Id
     *
     * @return the value of tb_wx_menuset.Id
     *
     * @mbggenerated Wed Sep 10 14:07:43 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wx_menuset.Id
     *
     * @param id the value for tb_wx_menuset.Id
     *
     * @mbggenerated Wed Sep 10 14:07:43 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wx_menuset.menu_name
     *
     * @return the value of tb_wx_menuset.menu_name
     *
     * @mbggenerated Wed Sep 10 14:07:43 CST 2014
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wx_menuset.menu_name
     *
     * @param menuName the value for tb_wx_menuset.menu_name
     *
     * @mbggenerated Wed Sep 10 14:07:43 CST 2014
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wx_menuset.menu_type
     *
     * @return the value of tb_wx_menuset.menu_type
     *
     * @mbggenerated Wed Sep 10 14:07:43 CST 2014
     */
    public String getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wx_menuset.menu_type
     *
     * @param menuType the value for tb_wx_menuset.menu_type
     *
     * @mbggenerated Wed Sep 10 14:07:43 CST 2014
     */
    public void setMenuType(String menuType) {
        this.menuType = menuType;
    }

   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wx_menuset.url
     *
     * @return the value of tb_wx_menuset.url
     *
     * @mbggenerated Wed Sep 10 14:07:43 CST 2014
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wx_menuset.url
     *
     * @param url the value for tb_wx_menuset.url
     *
     * @mbggenerated Wed Sep 10 14:07:43 CST 2014
     */
    public void setUrl(String url) {
        this.url = url;
    }
}