package com.bbf.wxpay;
public class WxPayNotify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_weixin_notify.Id
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_weixin_notify.app_id
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_weixin_notify.open_id
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_weixin_notify.notify_id
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    private String notifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_weixin_notify.transaction_id
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    private String transactionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_weixin_notify.out_trade_no
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_weixin_notify.time_end
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    private String timeEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_weixin_notify.trade_state
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    private Integer tradeState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_weixin_notify.handle_status
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    private Integer handleStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_weixin_notify.Id
     *
     * @return the value of tb_pay_weixin_notify.Id
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_weixin_notify.Id
     *
     * @param id the value for tb_pay_weixin_notify.Id
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_weixin_notify.app_id
     *
     * @return the value of tb_pay_weixin_notify.app_id
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_weixin_notify.app_id
     *
     * @param appId the value for tb_pay_weixin_notify.app_id
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_weixin_notify.open_id
     *
     * @return the value of tb_pay_weixin_notify.open_id
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_weixin_notify.open_id
     *
     * @param openId the value for tb_pay_weixin_notify.open_id
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_weixin_notify.notify_id
     *
     * @return the value of tb_pay_weixin_notify.notify_id
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    public String getNotifyId() {
        return notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_weixin_notify.notify_id
     *
     * @param notifyId the value for tb_pay_weixin_notify.notify_id
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    public void setNotifyId(String notifyId) {
        this.notifyId = notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_weixin_notify.transaction_id
     *
     * @return the value of tb_pay_weixin_notify.transaction_id
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_weixin_notify.transaction_id
     *
     * @param transactionId the value for tb_pay_weixin_notify.transaction_id
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_weixin_notify.out_trade_no
     *
     * @return the value of tb_pay_weixin_notify.out_trade_no
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_weixin_notify.out_trade_no
     *
     * @param outTradeNo the value for tb_pay_weixin_notify.out_trade_no
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_weixin_notify.time_end
     *
     * @return the value of tb_pay_weixin_notify.time_end
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    public String getTimeEnd() {
        return timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_weixin_notify.time_end
     *
     * @param timeEnd the value for tb_pay_weixin_notify.time_end
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    public void setTimeEnd(String timeEnd) {
        this.timeEnd = timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_weixin_notify.trade_state
     *
     * @return the value of tb_pay_weixin_notify.trade_state
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    public Integer getTradeState() {
        return tradeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_weixin_notify.trade_state
     *
     * @param tradeState the value for tb_pay_weixin_notify.trade_state
     *
     * @mbggenerated Wed Aug 27 09:56:35 CST 2014
     */
    public void setTradeState(Integer tradeState) {
        this.tradeState = tradeState;
    }

	public Integer getHandleStatus() {
		return handleStatus;
	}

	public void setHandleStatus(Integer handleStatus) {
		this.handleStatus = handleStatus;
	}

     
}