package com.bbf.wxpay;

public class WxPayFeedBack {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_weixin_feedback.trans_id
     *
     * @mbggenerated Thu Aug 21 10:26:28 CST 2014
     */
    private String transId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_weixin_feedback.open_id
     *
     * @mbggenerated Thu Aug 21 10:26:28 CST 2014
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_weixin_feedback.app_id
     *
     * @mbggenerated Thu Aug 21 10:26:28 CST 2014
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_weixin_feedback.rt_time_stamp
     *
     * @mbggenerated Thu Aug 21 10:26:28 CST 2014
     */
    private String rtTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_weixin_feedback.feed_back_id
     *
     * @mbggenerated Thu Aug 21 10:26:28 CST 2014
     */
    private String feedBackId;
    
    private int status; //0=用户确认， 1=待处理，2=客户拒绝维权确认
    
    private int handleStatus; //0=已通知客服， 1=未通知客服
    
    
    
    
    
    
    public int getHandleStatus() {
		return handleStatus;
	}

	public void setHandleStatus(int handleStatus) {
		this.handleStatus = handleStatus;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	/**
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column tb_pay_weixin_feedback.reason
    *
    * @mbggenerated Thu Aug 21 10:26:28 CST 2014
    */
   private String reason;

   /**
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column tb_pay_weixin_feedback.solution
    *
    * @mbggenerated Thu Aug 21 10:26:28 CST 2014
    */
   private String solution;

   /**
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column tb_pay_weixin_feedback.ext_info
    *
    * @mbggenerated Thu Aug 21 10:26:28 CST 2014
    */
   private String extInfo;

   /**
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column tb_pay_weixin_feedback.pic_url
    *
    * @mbggenerated Thu Aug 21 10:26:28 CST 2014
    */
   private String picUrl;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column tb_pay_weixin_feedback.reason
    *
    * @return the value of tb_pay_weixin_feedback.reason
    *
    * @mbggenerated Thu Aug 21 10:26:28 CST 2014
    */
   public String getReason() {
       return reason;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column tb_pay_weixin_feedback.reason
    *
    * @param reason the value for tb_pay_weixin_feedback.reason
    *
    * @mbggenerated Thu Aug 21 10:26:28 CST 2014
    */
   public void setReason(String reason) {
       this.reason = reason;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column tb_pay_weixin_feedback.solution
    *
    * @return the value of tb_pay_weixin_feedback.solution
    *
    * @mbggenerated Thu Aug 21 10:26:28 CST 2014
    */
   public String getSolution() {
       return solution;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column tb_pay_weixin_feedback.solution
    *
    * @param solution the value for tb_pay_weixin_feedback.solution
    *
    * @mbggenerated Thu Aug 21 10:26:28 CST 2014
    */
   public void setSolution(String solution) {
       this.solution = solution;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column tb_pay_weixin_feedback.ext_info
    *
    * @return the value of tb_pay_weixin_feedback.ext_info
    *
    * @mbggenerated Thu Aug 21 10:26:28 CST 2014
    */
   public String getExtInfo() {
       return extInfo;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column tb_pay_weixin_feedback.ext_info
    *
    * @param extInfo the value for tb_pay_weixin_feedback.ext_info
    *
    * @mbggenerated Thu Aug 21 10:26:28 CST 2014
    */
   public void setExtInfo(String extInfo) {
       this.extInfo = extInfo;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column tb_pay_weixin_feedback.pic_url
    *
    * @return the value of tb_pay_weixin_feedback.pic_url
    *
    * @mbggenerated Thu Aug 21 10:26:28 CST 2014
    */
   public String getPicUrl() {
       return picUrl;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column tb_pay_weixin_feedback.pic_url
    *
    * @param picUrl the value for tb_pay_weixin_feedback.pic_url
    *
    * @mbggenerated Thu Aug 21 10:26:28 CST 2014
    */
   public void setPicUrl(String picUrl) {
       this.picUrl = picUrl;
   }
   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_weixin_feedback.trans_id
     *
     * @return the value of tb_pay_weixin_feedback.trans_id
     *
     * @mbggenerated Thu Aug 21 10:26:28 CST 2014
     */
    public String getTransId() {
        return transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_weixin_feedback.trans_id
     *
     * @param transId the value for tb_pay_weixin_feedback.trans_id
     *
     * @mbggenerated Thu Aug 21 10:26:28 CST 2014
     */
    public void setTransId(String transId) {
        this.transId = transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_weixin_feedback.open_id
     *
     * @return the value of tb_pay_weixin_feedback.open_id
     *
     * @mbggenerated Thu Aug 21 10:26:28 CST 2014
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_weixin_feedback.open_id
     *
     * @param openId the value for tb_pay_weixin_feedback.open_id
     *
     * @mbggenerated Thu Aug 21 10:26:28 CST 2014
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_weixin_feedback.app_id
     *
     * @return the value of tb_pay_weixin_feedback.app_id
     *
     * @mbggenerated Thu Aug 21 10:26:28 CST 2014
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_weixin_feedback.app_id
     *
     * @param appId the value for tb_pay_weixin_feedback.app_id
     *
     * @mbggenerated Thu Aug 21 10:26:28 CST 2014
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_weixin_feedback.rt_time_stamp
     *
     * @return the value of tb_pay_weixin_feedback.rt_time_stamp
     *
     * @mbggenerated Thu Aug 21 10:26:28 CST 2014
     */
    public String getRtTimeStamp() {
        return rtTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_weixin_feedback.rt_time_stamp
     *
     * @param rtTimeStamp the value for tb_pay_weixin_feedback.rt_time_stamp
     *
     * @mbggenerated Thu Aug 21 10:26:28 CST 2014
     */
    public void setRtTimeStamp(String rtTimeStamp) {
        this.rtTimeStamp = rtTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_weixin_feedback.feed_back_id
     *
     * @return the value of tb_pay_weixin_feedback.feed_back_id
     *
     * @mbggenerated Thu Aug 21 10:26:28 CST 2014
     */
    public String getFeedBackId() {
        return feedBackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_weixin_feedback.feed_back_id
     *
     * @param feedBackId the value for tb_pay_weixin_feedback.feed_back_id
     *
     * @mbggenerated Thu Aug 21 10:26:28 CST 2014
     */
    public void setFeedBackId(String feedBackId) {
        this.feedBackId = feedBackId;
    }
}